base_configs:
  - configs/datasets/nuscenes.yaml
  - configs/models/radar_only.yaml
  - configs/hardware/gpu_single.yaml
  - configs/debug.yaml

random_seed: 42
device: "cuda"
checkpoint_path: null

# General parameters.
image:
  original_size: [900, 1600]
  final_size: [320, 800]
  feature_downsample: 8

bev_grid:
  x_bounds: [-50.0, 50.0, 0.5]
  y_bounds: [-50.0, 50.0, 0.5]
  z_bounds: [-5.0, 3.0, 8.0]

latent_grid:
  x_bounds: [-51.2, 51.2, 0.4]
  y_bounds: [-51.2, 51.2, 0.4]

wandb:
  enable: true
  project: "bevradar"
  experiment_name: "camera_only"
  tags: ["camera_radar", "nuscenes"]

# Optimization.
trainer:
  accelerator: "cuda"
  max_epochs: 40
  precision: "32-true"
  effective_batch_size: 32
  gradient_clip_val: 1.0

losses:
  aux_loss_weight: 0.4

optim:
  name: "AdamW"
  lr: 0.0003
  weight_decay: 0.01
  betas: [0.9, 0.999]

scheduler:
  name: "CosineAnnealingLRWithWarmup"
  num_warmup_epochs: 1